package com.apprenda.jenkins.plugins.apprenda;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.ws.rs.core.Response;

import hudson.util.Secret;
import utils.ApprendaRestUtility;;

/*
     A lot of the heavier lifting and communication with Apprenda is done here.
 */

public class ApprendaClient {
	private final String url;
	private final boolean bypassSSL;
	private String token = null;
	private Logger logger;

	// Constructor takes in instance URL and the flag whether to bypass SSL
	// validation.
	public ApprendaClient(String url, boolean bypassSSL) {
		this.url = url;
		this.bypassSSL = bypassSSL;
		logger = Logger.getLogger("jenkins.plugins.apprenda");
	}

	public boolean authenticate(ApprendaCredentials credentials) throws Exception {
		try {
			logger.log(Level.INFO, "Attempting to authenticate to Apprenda with username " + credentials.getUsername()
					+ " and tenant alias " + credentials.getTenant() + ".");
			;
			JsonObject json = Json.createObjectBuilder().add("username", credentials.getUsername())
					.add("password", Secret.toString(credentials.getPassword()))
					.add("tenantAlias", credentials.getTenant()).build();

			String AUTH_PATH = "authentication/api/v1/sessions/developer";
			Response response = new ApprendaRestUtility().PostResponseRequest(bypassSSL, getUrl(), AUTH_PATH, json);
			if (response.getStatus() != 201) {
				logger.log(Level.WARNING, "Authentication Failed.");
				return false;
			}
			JsonObject jsonObject = response.readEntity(JsonObject.class);
			this.token = jsonObject.getString("apprendaSessionToken");
			System.out.println("Successfully authenticated. Token: " + this.token);
			return true;
		} catch (Exception e) {
			logger.log(Level.SEVERE, e.getLocalizedMessage(), e);
			return false;
		}
	}

	// this method calls the Apprenda REST API to create a new version
	public Boolean newAppVersion(String appAlias, String versionAlias) {
		try {
			JsonObject newVersion = Json.createObjectBuilder().add("Name", versionAlias).add("Alias", versionAlias)
					.add("Description", "Version Auto-generated by Apprenda-Jenkins plugin.").build();
			logger.log(Level.INFO, "Step 1: Create New Version: " + versionAlias);
			Response createVersion = new ApprendaRestUtility(token).PostResponseRequest(bypassSSL, getUrl(),
					"developer/api/v1/versions/" + appAlias, newVersion);
			if (createVersion.getStatus() == 201) {
				logger.log(Level.INFO, "New Version Created");
				return true;
			} else {
				logger.log(Level.WARNING,
						"Version was not created. Please check to see if the version is taken, or the application exists. Full response: "
								+ createVersion.readEntity(JsonObject.class).toString());
				return false;
			}
		} catch (Exception e) {
			// logger.log(Level.SEVERE, "Exception occurred during creation of
			// new version.");
			return false;
		}
	}

	// this method patches the application to a specific version, with a file
	// that contains the new binaries
	public Boolean patchApp(String appAlias, String versionAlias, File appFile, String stage) {
		try {
			InputStream fileInStream = new FileInputStream(appFile);
			logger.log(Level.INFO, "Starting promotion of application: " + appAlias + " and version: " + versionAlias);
			logger.log(Level.INFO, "Starting patching of application: " + appFile.getAbsolutePath());
			String VERSION_PATH = "developer/api/v1/versions/";
			Response response = new ApprendaRestUtility(token).PatchApplication(bypassSSL, getUrl(),
					VERSION_PATH + appAlias + "/" + versionAlias, stage, fileInStream);
			if (response.getStatus() == 200) {
				logger.log(Level.INFO, "Promotion complete.");
				return true;
			} else {
				logger.log(Level.WARNING,
						"An error occurred during the patching of your application. Here's what I got: "
								+ response.toString());
				return false;
			}
		} catch (Exception e) {
			logger.log(Level.SEVERE, e.getMessage(), e);
			return false;
		}
	}

	// this method patches the creates an application to a specific version,
	// with a file
	// that contains the new binaries
	public Boolean createApp(String appAlias, File appFile, String stage) {
		try {
			logger.log(Level.INFO, "Starting creation of application: " + appAlias);
			String PATH = "developer/api/v1/apps";
			Response response = new ApprendaRestUtility(token).CreateApplication(bypassSSL, getUrl(), PATH, appAlias);
			logger.log(Level.INFO, "Starting patching of application: " + appFile.getAbsolutePath());
			if (response.getStatus() == 201) {
				logger.log(Level.INFO, "Creation succesful.");
				return patchApp(appAlias, "v1", appFile, stage);
			} else {
				logger.log(Level.WARNING,
						"An error occurred during the patching of your application. Here's what I got: "
								+ response.toString());
				return false;
			}
		} catch (Exception e) {
			logger.log(Level.SEVERE, e.getMessage(), e);
			return false;
		}
	}

	public String getUrl() {
		return url;
	}

	// this method get all of the versions
	public JsonArray GetAppAliasVersions(String appAlias) throws Exception {
		if (token == null) {
			throw new SecurityException("Authentication failed previously, no session token exists.");
		}
		Response getVersions = new ApprendaRestUtility(token).GetResponseRequest(bypassSSL, getUrl(),
				"developer/api/v1/versions/" + appAlias, null);
		if (getVersions.getStatus() == 200) {
			return getVersions.readEntity(JsonArray.class);
		} else {
			return null;
		}
	}

	public ArrayList<String> GetAppAliases(String username) throws SecurityException {
		try {
			if (token == null)
				throw new SecurityException("Authentication failed previously, no session token exists.");
			Response getAliases = new ApprendaRestUtility(token).GetResponseRequest(bypassSSL, getUrl(),
					"developer/api/v1/apps", null);
			if (getAliases.getStatus() == 200) {
				JsonArray jsonArray = getAliases.readEntity(JsonArray.class);
				logger.log(Level.INFO, jsonArray.toString());
				ArrayList<String> aliasArray = new ArrayList<String>();
				for (int i = 0; i < jsonArray.size(); i++) {
					JsonObject obj = jsonArray.getJsonObject(i);
					aliasArray.add(obj.getString("alias"));
				}
				return aliasArray;
			} else {
				logger.log(Level.WARNING,
						"Failed to get application aliases. Response returned: " + getAliases.getStatus());
				logger.log(Level.WARNING, "Response Body: " + getAliases.readEntity(String.class));
				return null;
			}
		} catch (Exception e) {
			logger.log(Level.SEVERE, e.getMessage(), e);
			return null;
		}
	}
}